### ISSUE TITLE
prova

### ISSUE THREAD

**Issue by leonardjaner** [perebarberan/gitpractiques#1]
quins canvis he de fer

**Comment by perebarberan** [comment]
estic perdut.

**Comment by leonardjaner** [comment]
#Aixo ha de ser util
segur
##si juguem una mica ho veurem
hem de mirar de jugar una mica. estic segur que aixo ens ha de servir per les classes

**Comment by perebarberan** [comment]
Segurament. Hem de fer proves per veure com ho fem servir.
